### ISSUE TITLE
Unmaintained flake8-copyright not compatible with flake8>=5.0.0

### ISSUE THREAD

**Issue by natalian98** [canonical/template-operator#32]
The copyright linter plugin `flake8-copyright` is no more usable since a new version of its dependency, `flake8` 5.0.0+, was released. An [issue](https://github.com/savoirfairelinux/flake8-copyright/issues/18) is already opened in its repo.
`flake8` has constrained the plugin code's entrypoint to be the error code prefix that should be emitted from it (C801).
While executing the lint tests, copyright check will fail with:
```
plugin code for `flake8-copyright[flake8_copyright]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

A [PR](https://github.com/savoirfairelinux/flake8-copyright/pull/9) fixing it is opened since 2018, but the project doesn't seem to be maintained anymore.
There is a [fork](https://github.com/televi/flake8-copyright) containing that fix which resolves the issue.

Is it acceptable to pin `flake8-copyright` to that unofficial fork in our charms or should we create our own?

**Comment by simskij** [comment]
The PR was actually merged just after you created this one, so should be safe to just update the official one for now! 😅 

![image](https://user-images.githubusercontent.com/1596025/183403913-4a34a18a-2268-468b-a0f7-516ba100033f.png)

**Comment by natalian98** [comment]
That's great :+1: Thanks!
I'll close this issue, I guess we need to consider each case separately if anything similar appears in future.
