### ISSUE TITLE
`codespell` command in linting is broken with `tox>=4`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/template-operator#43]
### Bug Description

See [this issue](https://github.com/canonical/kubeflow-ci/issues/40) for more details.  With tox 4.0, our invocation of `codespell` during `tox -e lint` is broken, seemingly due to a change in how the `{toxinidir}` variable works or maybe how they parse commands and wildcards.

### To Reproduce

`pip install -U "tox>=4"; tox -e lint` 

### Environment

Any environment with tox>=4

### Relevant log output

```shell
See https://github.com/canonical/kubeflow-ci/issues/40
```

**Comment by jnsgruk** [comment]
Fixed in #45
